CREATE INDEX `asset_history_asset_id_idx` ON `asset_history` (`asset_id`);--> statement-breakpoint
CREATE INDEX `asset_snapshot_items_snapshot_id_idx` ON `asset_snapshot_items` (`snapshot_id`);--> statement-breakpoint
CREATE INDEX `asset_snapshot_items_asset_id_idx` ON `asset_snapshot_items` (`asset_id`);--> statement-breakpoint
CREATE INDEX `assets_workspace_id_idx` ON `assets` (`workspace_id`);--> statement-breakpoint
CREATE INDEX `assets_ws_status_deleted_idx` ON `assets` (`workspace_id`,`status`,`deleted_at`);--> statement-breakpoint
CREATE INDEX `audit_logs_workspace_id_idx` ON `audit_logs` (`workspace_id`);--> statement-breakpoint
CREATE INDEX `audit_logs_user_id_idx` ON `audit_logs` (`user_id`);--> statement-breakpoint
CREATE INDEX `audit_logs_created_at_idx` ON `audit_logs` (`created_at`);--> statement-breakpoint
CREATE INDEX `audit_logs_ws_entity_action_idx` ON `audit_logs` (`workspace_id`,`entity_type`,`entity_id`,`action`);--> statement-breakpoint
CREATE INDEX `budgets_ws_month_year_currency_idx` ON `budgets` (`workspace_id`,`month`,`year`,`currency`);--> statement-breakpoint
CREATE INDEX `workspace_invitations_workspace_id_idx` ON `workspace_invitations` (`workspace_id`);--> statement-breakpoint
CREATE INDEX `users_workspace_id_idx` ON `users` (`workspace_id`);--> statement-breakpoint
CREATE INDEX `sessions_user_id_idx` ON `sessions` (`user_id`);--> statement-breakpoint
CREATE INDEX `transactions_workspace_id_idx` ON `transactions` (`workspace_id`);--> statement-breakpoint
CREATE INDEX `transactions_asset_id_idx` ON `transactions` (`asset_id`);--> statement-breakpoint
CREATE INDEX `transactions_transaction_date_idx` ON `transactions` (`transaction_date`);--> statement-breakpoint
CREATE INDEX `transactions_category_id_idx` ON `transactions` (`category_id`);--> statement-breakpoint
CREATE INDEX `transactions_ws_type_currency_date_idx` ON `transactions` (`workspace_id`,`type`,`currency`,`transaction_date`);--> statement-breakpoint
CREATE INDEX `transactions_ws_cat_type_currency_date_idx` ON `transactions` (`workspace_id`,`category_id`,`type`,`currency`,`transaction_date`);--> statement-breakpoint
CREATE INDEX `transactions_ws_user_date_idx` ON `transactions` (`workspace_id`,`created_by_user_id`,`transaction_date`);--> statement-breakpoint
CREATE INDEX `transactions_to_asset_id_idx` ON `transactions` (`to_asset_id`);