export const ALLOWLIST_QUERY_IDS = {
  AUTH_TOKEN_LOOKUP: 'AUTH_TOKEN_LOOKUP',
  AUTH_API_KEY_VALIDATE_PREFIX: 'AUTH_API_KEY_VALIDATE_PREFIX',
  GLOBAL_EXCHANGE_RATES_READ: 'GLOBAL_EXCHANGE_RATES_READ',
  ADMIN_CLI_LIST_WORKSPACES: 'ADMIN_CLI_LIST_WORKSPACES',
  ADMIN_CLI_DELETE_WORKSPACE: 'ADMIN_CLI_DELETE_WORKSPACE',
  SYSTEM_SEED_BACKFILL: 'SYSTEM_SEED_BACKFILL',
} as const;

const GLOBAL_QUERY_ALLOWLIST = new Set<string>(Object.values(ALLOWLIST_QUERY_IDS));

export function isAllowlistedGlobalQuery(queryId: string): boolean {
  return GLOBAL_QUERY_ALLOWLIST.has(queryId);
}
