/**
 * POST /api/auth/login/verify-mfa
 *
 * Verify MFA code during login flow.
 * Requires a pending MFA cookie generated by /api/auth/login.
 */

import type { APIRoute } from 'astro';
import { auth } from '@/lib/auth/lucia';
import { mfaService } from '@/services';
import { logAuditEvent } from '@/lib/audit-log';
import {
  createErrorResponseResponse,
  createSuccessResponse,
  STANDARD_RESPONSE_HEADERS,
} from '@/types/api';
import { logError } from '@/lib/utils';
import { eq } from 'drizzle-orm';
import {
  applyRateLimitHeaders,
  checkRateLimit,
  createRateLimitResponse,
  RATE_LIMIT_PRESETS,
} from '@/lib/rate-limit';

export const prerender = false;

const MFA_PENDING_COOKIE = 'mfa_pending';

export const POST: APIRoute = async ({ request, cookies, clientAddress }) => {
  const rateLimitResult = checkRateLimit(request, RATE_LIMIT_PRESETS.auth, clientAddress);
  if (!rateLimitResult.allowed) {
    return createRateLimitResponse(rateLimitResult, 'Too many MFA attempts. Please wait.');
  }

  try {
    const pendingCookieValue = cookies.get(MFA_PENDING_COOKIE)?.value;
    if (!pendingCookieValue) {
      return createErrorResponseResponse('NO_PENDING_MFA', 'No pending MFA verification', 400);
    }

    let userId = '';
    try {
      const parsed = JSON.parse(decodeURIComponent(pendingCookieValue));
      userId = typeof parsed.userId === 'string' ? parsed.userId : '';
    } catch {
      return createErrorResponseResponse('INVALID_STATE', 'Invalid MFA session', 400);
    }

    if (!userId) {
      return createErrorResponseResponse('INVALID_STATE', 'Invalid MFA session', 400);
    }

    const body = await request.json();
    const code = typeof body.code === 'string' ? body.code.trim() : '';
    const isBackupCode = body.isBackupCode === true;

    if (!code) {
      return createErrorResponseResponse('INVALID_INPUT', 'Verification code is required', 400);
    }

    let isValid = false;
    if (isBackupCode) {
      isValid = await mfaService.verifyAndConsumeBackupCode(userId, code);
    } else {
      isValid = await mfaService.verifyTotp(userId, code);
    }

    if (!isValid) {
      const errorResponse = createErrorResponseResponse(
        'INVALID_MFA_CODE',
        'Invalid verification code',
        401
      );
      return applyRateLimitHeaders(errorResponse, rateLimitResult);
    }

    const session = await auth.createSession(userId, {});
    const sessionCookie = auth.createSessionCookie(session.id);

    // Log MFA-verified login. Must never block authentication flow.
    try {
      const { db, getActiveSchema } = await import('@/db');
      const schema = getActiveSchema();
      const userRecord = await db.query.users.findFirst({
        where: eq(schema.users.id, userId),
        columns: { workspace_id: true },
      });

      if (userRecord?.workspace_id) {
        void logAuditEvent({
          workspaceId: userRecord.workspace_id,
          userId,
          action: 'login',
          entityType: 'session',
          entityId: session.id,
          newValue: { mfa: true, method: isBackupCode ? 'backup_code' : 'totp' },
        });
      }
    } catch {
      // Audit logging should never block login.
    }

    cookies.delete(MFA_PENDING_COOKIE, { path: '/' });

    const response = new Response(
      JSON.stringify(
        createSuccessResponse({
          verified: true,
        })
      ),
      {
        status: 200,
        headers: {
          ...STANDARD_RESPONSE_HEADERS,
          'Set-Cookie': sessionCookie.serialize(),
        },
      }
    );

    return applyRateLimitHeaders(response, rateLimitResult);
  } catch (error) {
    logError('MFA verification error', error);
    return createErrorResponseResponse('MFA_VERIFY_ERROR', 'Verification failed', 500);
  }
};
