#!/usr/bin/env bun

/**
 * DB Performance Analyzer
 *
 * Reads perf-results.json (written by performance-benchmark.test.ts)
 * and generates a markdown report for PR comments.
 *
 * Usage:
 *   bun test src/services/__tests__/performance-benchmark.test.ts
 *   bun run scripts/analyze-performance.ts > perf-report.md
 */

import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

interface BenchmarkResult {
  method: string;
  queries: number | null;
  maxQueries: number | null;
  durationMs: number;
  maxMs: number;
  status: 'pass' | 'fail';
}

interface PerfData {
  results: BenchmarkResult[];
  dataScale: {
    transactions: number;
    categories: number;
    accounts: number;
    recurringTemplates: number;
  };
}

function formatMs(ms: number): string {
  return `${ms.toFixed(1)} ms`;
}

function getTimeStatus(actual: number, limit: number): string {
  const pct = (actual / limit) * 100;
  if (pct > 100) return '🔴 Over';
  if (pct > 75) return '🟡 Near';
  return '✅ Pass';
}

function getQueryStatus(actual: number | null, limit: number | null): string {
  if (limit === null || actual === null) return '—';
  if (actual > limit) return '🔴 Over';
  if (actual > limit * 0.75) return '🟡 Near';
  return '✅ Pass';
}

function analyze(): string {
  const resultsPath = join(process.cwd(), 'perf-results.json');

  if (!existsSync(resultsPath)) {
    throw new Error(
      'perf-results.json not found. Run the benchmark test first:\n' +
        '  bun test src/services/__tests__/performance-benchmark.test.ts'
    );
  }

  const data: PerfData = JSON.parse(readFileSync(resultsPath, 'utf-8'));
  const { results, dataScale } = data;

  const failures = results.filter((r) => r.status === 'fail');
  const allPassed = failures.length === 0;

  let report = '## ⚡ DB Performance Report\n\n';

  // Data scale context
  report += `> Benchmark: ${dataScale.transactions.toLocaleString()} transactions, `;
  report += `${dataScale.categories} categories, ${dataScale.accounts} accounts, `;
  report += `${dataScale.recurringTemplates} recurring templates\n\n`;

  // Results table
  report += '### Results\n\n';
  report += '| Method | Queries | Limit | Time | Limit | Status |\n';
  report += '|--------|--------:|------:|-----:|------:|--------|\n';

  for (const r of results) {
    const qStr = r.queries !== null ? String(r.queries) : '—';
    const qMaxStr = r.maxQueries !== null ? `≤ ${r.maxQueries}` : '—';
    const qStatus = getQueryStatus(r.queries, r.maxQueries);
    const tStatus = getTimeStatus(r.durationMs, r.maxMs);
    const status = r.status === 'pass' ? '✅' : '🔴';

    // Use the worst status between query and time
    const displayStatus =
      qStatus.includes('🔴') || tStatus.includes('🔴')
        ? `${status} Fail`
        : qStatus.includes('🟡') || tStatus.includes('🟡')
          ? '🟡 Near limit'
          : '✅ Pass';

    report += `| \`${r.method}\` | ${qStr} | ${qMaxStr} | ${formatMs(r.durationMs)} | < ${r.maxMs} ms | ${displayStatus} |\n`;
  }

  // Summary
  report += '\n### ';
  if (allPassed) {
    report += '✅ All Checks Passed\n\n';
    report += 'All service methods are within query count and timing budgets.\n';
  } else {
    report += '🔴 Performance Regressions Detected\n\n';
    for (const f of failures) {
      const issues: string[] = [];
      if (f.maxQueries !== null && f.queries !== null && f.queries > f.maxQueries) {
        issues.push(`${f.queries} queries (limit: ${f.maxQueries})`);
      }
      if (f.durationMs >= f.maxMs) {
        issues.push(`${formatMs(f.durationMs)} (limit: ${f.maxMs} ms)`);
      }
      report += `- **\`${f.method}\`**: ${issues.join(', ')}\n`;
    }
    report +=
      '\nN+1 query patterns produce 12-50+ queries per call. If query counts are high, check for loops issuing individual queries instead of SQL aggregation.\n';
  }

  // Footer
  report += '\n---\n';
  const ghUrl = process.env.GITHUB_SERVER_URL || 'https://github.com';
  const ghRepo = process.env.GITHUB_REPOSITORY || 'owner/repo';
  const ghRun = process.env.GITHUB_RUN_ID || '0';
  report += `\n<sub>⚡ Generated by [db-performance workflow](${ghUrl}/${ghRepo}/actions/runs/${ghRun})</sub>\n`;

  return report;
}

try {
  const report = analyze();
  // eslint-disable-next-line no-console
  console.log(report);
  process.exit(0);
} catch (error) {
  console.error('Error analyzing performance:', error);
  process.exit(1);
}
